### PR TITLE
remove dev specific url generation

### PR DESCRIPTION
**Pull request by enochtsang**
We should be able to hit any server with or without `dev.calgaryscientific.com` if anything, we can put `calgaryscientific.local` as part of the search domain but even that I see as unnecessary. Let me know what you think.

### CODE REVIEW

**Comment by colefranz** [comment]
I don't know that this is true

**Comment by sararathje** [comment]
Our servers all require the .dev.calgaryscientific.com for SSL.

**Comment by enochtsang** [comment]
@sararathje That makes sense for SSL, we still need to do something about this if we want the  statusboard to not be dev specific later on though.

**Comment by DavidGamba** [comment]
In dev we use *.csi-hub.com for some services. I would like the option of adding servers like that.
Why can't the server name be the FQDN?

**Pull request closed without merging**
